spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data;DB_CLOSE_ON_EXIT=FALSE
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
logging:
    level:
        root: INFO
app:
  string: stringProperty
  list:
    - listProperty1
    - listProperty2